import { Product } from './product.interface';

export const PRODUCT: Product[] = [
    { id: 1, name: 'name1', title: 'title1', describe: 'describe', url: '../src/assets/img/card1.jpg' },
    { id: 2, name: 'name2', title: 'title2', describe: 'describe', url: '../src/assets/img/card2.jpg' },
    { id: 3, name: 'name3', title: 'title3', describe: 'describe', url: '../src/assets/img/card3.jpg' },
    { id: 4, name: 'name4', title: 'title4', describe: 'describe', url: '../src/assets/img/card4.jpg' },
    { id: 5, name: 'name5', title: 'title5', describe: 'describe', url: '../src/assets/img/card5.jpg' },
    { id: 6, name: 'name6', title: 'title6', describe: 'describe', url: '../src/assets/img/card6.jpg' },
    { id: 7, name: 'name7', title: 'title7', describe: 'describe', url: '../src/assets/img/card7.jpg' },
    { id: 8, name: 'name8', title: 'title8', describe: 'describe', url: '../src/assets/img/card8.jpg' },
    { id: 9, name: 'name9', title: 'title9', describe: 'describe', url: '../src/assets/img/card9.jpg' },
    { id: 10, name: 'name10', title: 'title10', describe: 'describe', url: '../src/assets/img/card10.jpg' },
    { id: 11, name: 'name11', title: 'title11', describe: 'describe', url: '../src/assets/img/1.jpg' },
    { id: 12, name: 'name12', title: 'title12', describe: 'describe', url: '../src/assets/img/2.jpg' },
    { id: 13, name: 'name13', title: 'title13', describe: 'describe', url: '../src/assets/img/2.jpg' },
    { id: 14, name: 'name14', title: 'title14', describe: 'describe', url: '../src/assets/img/3.jpg' },
    { id: 15, name: 'name15', title: 'title15', describe: 'describe', url: '../src/assets/img/4.jpg' },
    { id: 16, name: 'name16', title: 'title16', describe: 'describe', url: '../src/assets/img/3.jpg' },
    { id: 17, name: 'name17', title: 'title17', describe: 'describe', url: '../src/assets/img/4.jpg' },
    { id: 18, name: 'name18', title: 'title18', describe: 'describe', url: '../src/assets/img/7.jpg' },
    { id: 19, name: 'name19', title: 'title19', describe: 'describe', url: '../src/assets/img/8.jpg' },
    { id: 20, name: 'name20', title: 'title20', describe: 'describe', url: '../src/assets/img/9.jpg' },
    { id: 21, name: 'name21', title: 'title21', describe: 'describe', url: '../src/assets/img/logo.png' },
    { id: 22, name: 'name22', title: 'title22', describe: 'describe', url: '../src/assets/img/img2.jpg' },
    { id: 23, name: 'name23', title: 'title23', describe: 'describe', url: '../src/assets/img/img24.jpg' },
    { id: 24, name: 'name24', title: 'title24', describe: 'describe', url: '../src/assets/img/img4.jpg' },
    { id: 25, name: 'name25', title: 'title25', describe: 'describe', url: '../src/assets/img/3.jpg' },
    { id: 26, name: 'name26', title: 'title26', describe: 'describe', url: '../src/assets/img/3.jpg' },
    { id: 27, name: 'name27', title: 'title27', describe: 'describe', url: '../src/assets/img/3.jpg' },
    { id: 28, name: 'name28', title: 'title28', describe: 'describe', url: 'http://lorempixel.com/279/180/'},
    { id: 29, name: 'name29', title: 'title29', describe: 'describe', url: 'http://lorempixel.com/279/182/' },
    { id: 30, name: 'name30', title: 'title30', describe: 'describe', url: 'http://lorempixel.com/279/183/' },
    { id: 31, name: 'name31', title: 'title31', describe: 'describe', url: 'http://lorempixel.com/279/184/' },
    { id: 32, name: 'name32', title: 'title32', describe: 'describe', url: 'http://lorempixel.com/279/185/' },
    { id: 33, name: 'name33', title: 'title33', describe: 'describe', url: 'http://lorempixel.com/279/186/' },
    { id: 34, name: 'name34', title: 'title34', describe: 'describe', url: 'http://lorempixel.com/279/187/' },
    { id: 35, name: 'name35', title: 'title35', describe: 'describe', url: 'http://lorempixel.com/279/188/' },
    { id: 36, name: 'name36', title: 'title36', describe: 'describe', url: 'http://lorempixel.com/279/189/' },
    { id: 37, name: 'name37', title: 'title37', describe: 'describe', url: 'http://lorempixel.com/279/190/' },
    { id: 38, name: 'name38', title: 'title38', describe: 'describe', url: 'http://lorempixel.com/279/191/' },
    { id: 39, name: 'name39', title: 'title39', describe: 'describe', url: 'http://lorempixel.com/279/192/' },
    { id: 40, name: 'name40', title: 'title40', describe: 'describe', url: 'http://lorempixel.com/279/171/' },
    { id: 41, name: 'name41', title: 'title41', describe: 'describe', url: 'http://lorempixel.com/279/172/' },
    { id: 42, name: 'name42', title: 'title42', describe: 'describe', url: 'http://lorempixel.com/279/173/' },
    { id: 43, name: 'name43', title: 'title43', describe: 'describe', url: 'http://lorempixel.com/279/174/' },
    { id: 44, name: 'name44', title: 'title44', describe: 'describe', url: 'http://lorempixel.com/279/175/' },
    { id: 45, name: 'name45', title: 'title45', describe: 'describe', url: 'http://lorempixel.com/279/176/' },
    { id: 46, name: 'name46', title: 'title46', describe: 'describe', url: 'http://lorempixel.com/279/177/' },
    { id: 47, name: 'name47', title: 'title47', describe: 'describe', url: 'http://lorempixel.com/279/178/' },
    { id: 48, name: 'name48', title: 'title48', describe: 'describe', url: 'http://lorempixel.com/279/179/' },
    { id: 49, name: 'name49', title: 'title49', describe: 'describe', url: 'http://lorempixel.com/279/170/' },
    { id: 50, name: 'name50', title: 'title50', describe: 'describe', url: 'http://lorempixel.com/279/169/' }
];